name: hack-verify
on:
  pull_request:
  push:
      branches: [master]

env:
  REPORT_DIR: tmp/junit

jobs:
  hack-verify:
    runs-on: ubuntu-latest
    container:
      image: us-east1-docker.pkg.dev/ret-edge-pltf-preprod-infra/preprod/build:latest
      credentials:
        username: _json_key_base64
        password: ${{ secrets.RET_INFRA_SACCOUNT }}
    steps:
    - name: Checkout
      run: github-actions-clone-repo.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: GitHub authentication
      run: |
        echo "machine github.com" > "$HOME/.netrc"
        echo "login ${{ secrets.EE_GITHUB_USER }}" >> ~/.netrc
        echo "password ${{ secrets.EE_GITHUB_TOKEN }}" >> ~/.netrc
    - run: just verify
      env:
        GOLANGCI_LINT_CACHE: '/__w/_tool/.cache/golangci-lint'
    # - name: Convert kpt results to JUnit
    #   run: convert-kpt2junit.sh
    #   env:
    #     REPORT_DIR: ${{ env.REPORT_DIR }}
    # - name: Upload JUnit Reports
    #   run: art "${{ env.REPORT_DIR }}"
    - name: Post-Execution Cleanup
      run: delete-repo.sh

